version: "3.8"
services:
  aprkits:
    image: aprkits
    container_name: aprkits
    build:
      context: .
    volumes:
      - ./:/app/aprkits
      - ../../../../datasets:/datasets
    ports:
      - "${PORT}:6006"
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1', '2', '3']
              capabilities: [gpu]
    tty: true
    command: tensorboard --logdir=.cache/data/summary/ --port=6006 --bind_all
